{
 "title": "Consommations de chauffage",
 "time": { "from": "now-400d", "to": "now" },
 "templating": {
  "list": [
   { "name": "uc", "label": "Valeur UC", "query": "0.10" }
  ]
 },
 "panels": [
  {
   "title": "Total période",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "SELECT (pointsComptage.numeroPointComptage || '- ' || pointsComptage.libellePiece) as piece, sum(corrigeeSansPonderationDju)* ${uc} as releve \nFROM consommationChauffage\nJOIN pointsComptage\nON pointsComptage.numeroPointComptage = consommationChauffage.numeroPointComptage\nWHERE date >= $__from / 1000 and date < $__to / 1000\ngroup by pointsComptage.numeroPointComptage\nORDER BY date, pointsComptage.numeroPointComptage\n",
     "rawQueryText": "SELECT (pointsComptage.numeroPointComptage || '- ' || pointsComptage.libellePiece) as piece, sum(corrigeeSansPonderationDju)* ${uc} as releve \nFROM consommationChauffage\nJOIN pointsComptage\nON pointsComptage.numeroPointComptage = consommationChauffage.numeroPointComptage\nWHERE date >= $__from / 1000 and date < $__to / 1000\ngroup by pointsComptage.numeroPointComptage\nORDER BY date, pointsComptage.numeroPointComptage\n"
    }
   ]
  },
  {
   "title": "Usage par pièce",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT (pointsComptage.numeroPointComptage || '- ' || pointsComptage.libellePiece) as piece, sum(corrigeeSansPonderationDju)* ${uc} as releve \nFROM consommationChauffage\nJOIN pointsComptage\nON pointsComptage.numeroPointComptage = consommationChauffage.numeroPointComptage\nWHERE date >= $__from / 1000 and date < $__to / 1000\ngroup by pointsComptage.numeroPointComptage\nORDER BY date, pointsComptage.numeroPointComptage\n",
     "rawQueryText": "SELECT (pointsComptage.numeroPointComptage || '- ' || pointsComptage.libellePiece) as piece, sum(corrigeeSansPonderationDju)* ${uc} as releve \nFROM consommationChauffage\nJOIN pointsComptage\nON pointsComptage.numeroPointComptage = consommationChauffage.numeroPointComptage\nWHERE date >= $__from / 1000 and date < $__to / 1000\ngroup by pointsComptage.numeroPointComptage\nORDER BY date, pointsComptage.numeroPointComptage\n"
    }
   ]
  },
  {
   "title": "Usage par pièce",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT (pointsComptage.numeroPointComptage || '- ' || pointsComptage.libellePiece) as piece, sum(corrigeeSansPonderationDju) as releve\nFROM consommationChauffage\nJOIN pointsComptage\nON pointsComptage.numeroPointComptage = consommationChauffage.numeroPointComptage\nWHERE date >= $__from / 1000 and date < $__to / 1000\ngroup by pointsComptage.numeroPointComptage\nORDER BY date, pointsComptage.numeroPointComptage\n",
     "rawQueryText": "SELECT (pointsComptage.numeroPointComptage || '- ' || pointsComptage.libellePiece) as piece, sum(corrigeeSansPonderationDju) as releve\nFROM consommationChauffage\nJOIN pointsComptage\nON pointsComptage.numeroPointComptage = consommationChauffage.numeroPointComptage\nWHERE date >= $__from / 1000 and date < $__to / 1000\ngroup by pointsComptage.numeroPointComptage\nORDER BY date, pointsComptage.numeroPointComptage\n"
    }
   ]
  },
  {
   "title": "Conso par pièce et par jour",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "targets": [
    {
     "queryText": "SELECT date, (pointsComptage.numeroPointComptage || '- ' || pointsComptage.libellePiece) as piece, corrigeeSansPonderationDju*$uc as releve\nFROM consommationChauffage\nJOIN pointsComptage\nON pointsComptage.numeroPointComptage = consommationChauffage.numeroPointComptage\nWHERE date >= $__from / 1000 and date < $__to / 1000\nORDER BY date, pointsComptage.numeroPointComptage\n",
     "rawQueryText": "SELECT date, (pointsComptage.numeroPointComptage || '- ' || pointsComptage.libellePiece) as piece, corrigeeSansPonderationDju*$uc as releve\nFROM consommationChauffage\nJOIN pointsComptage\nON pointsComptage.numeroPointComptage = consommationChauffage.numeroPointComptage\nWHERE date >= $__from / 1000 and date < $__to / 1000\nORDER BY date, pointsComptage.numeroPointComptage\n",
     "timeColumns": [ "date" ]
    },
    {
     "queryText": "SELECT date, temperatureMean, temperatureMin\nFROM historyTemperature\nWHERE date >= $__from / 1000 and date < $__to / 1000\nORDER BY date\n",
     "rawQueryText": "SELECT date, temperatureMean, temperatureMin\nFROM historyTemperature\nWHERE date >= $__from / 1000 and date < $__to / 1000\nORDER BY date\n",
     "timeColumns": [ "date" ]
    }
   ]
  },
  {
   "title": "Conso par pièce et par jour - SANS CORRECTION",
   "type": "timeseries",
   "description": "La correction consiste à corriger l'index par rapport à la taille du radiateur",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "targets": [
    {
     "queryText": "SELECT date, (pointsComptage.numeroPointComptage || '- ' || pointsComptage.libellePiece) as piece, bruteSansPonderationDju*$uc as releve\nFROM consommationChauffage\nJOIN pointsComptage\nON pointsComptage.numeroPointComptage = consommationChauffage.numeroPointComptage\nWHERE date >= $__from / 1000 and date < $__to / 1000\nORDER BY date, pointsComptage.numeroPointComptage\n",
     "rawQueryText": "SELECT date, (pointsComptage.numeroPointComptage || '- ' || pointsComptage.libellePiece) as piece, bruteSansPonderationDju*$uc as releve\nFROM consommationChauffage\nJOIN pointsComptage\nON pointsComptage.numeroPointComptage = consommationChauffage.numeroPointComptage\nWHERE date >= $__from / 1000 and date < $__to / 1000\nORDER BY date, pointsComptage.numeroPointComptage\n",
     "timeColumns": [ "date" ]
    }
   ]
  }
 ]
}